"use client";

import Link from "next/link";
import { useState } from "react";
import styles from "./queue.module.css";

export type LoaderQueueTrip = { id: string; departure: string | null; departureLabel: string; vehicleId: string; tripNumber: number; district: string; brand: string; stops: number; temperature: string; status: string; loading: boolean; changed: boolean; urgent: boolean };

export function LoaderQueue({ trips }: Readonly<{ trips: LoaderQueueTrip[] }>) {
  const [urgency, setUrgency] = useState("all");
  const [vehicle, setVehicle] = useState("all");
  const [status, setStatus] = useState("all");
  const [sort, setSort] = useState("departure");
  const vehicles = [...new Set(trips.map((trip) => trip.vehicleId))].sort();
  const visible = trips.filter((trip) => (urgency === "all" || trip.urgent) && (vehicle === "all" || trip.vehicleId === vehicle) && (status === "all" || (status === "LOADING" ? trip.loading : trip.status === status))).sort((a, b) => sort === "vehicle" ? a.vehicleId.localeCompare(b.vehicleId) : sort === "status" ? `${a.loading ? "LOADING" : a.status}`.localeCompare(`${b.loading ? "LOADING" : b.status}`) : (a.departure ?? "9999").localeCompare(b.departure ?? "9999"));
  return <><section className={styles.filters} aria-label="Trip queue filters"><label>Urgency<select value={urgency} onChange={(event) => setUrgency(event.target.value)}><option value="all">All trips</option><option value="fresh">Fresh before 08:00</option></select></label><label>Vehicle<select value={vehicle} onChange={(event) => setVehicle(event.target.value)}><option value="all">All vehicles</option>{vehicles.map((id) => <option key={id}>{id}</option>)}</select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="ALLOCATED">Not started</option><option value="LOADING">Loading</option><option value="LOADED">Loaded</option></select></label><label>Sort by<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="departure">Departure</option><option value="vehicle">Vehicle</option><option value="status">Status</option></select></label><span>{visible.length} of {trips.length} trips</span></section><section className={styles.tableCard}><div className={styles.tableHeader}><span>Departs</span><span>Vehicle</span><span>Trip</span><span>Stops</span><span>Temperature</span><span>Status</span><span /></div><div className={styles.tripRows}>{visible.map((trip) => { const state = trip.changed ? "Plan changed" : trip.loading ? "Loading" : trip.status === "LOADED" ? "Loaded" : "Not started"; return <article className={`${styles.tripRow} ${trip.changed ? styles.changed : ""} ${trip.urgent ? styles.urgent : ""}`} key={trip.id}><strong className={styles.departure}>{trip.departureLabel}</strong><b>{trip.vehicleId}</b><span className={styles.tripName}>Trip {trip.tripNumber} · {trip.district}<small>{trip.brand === "FRESH" ? "Fresh priority" : trip.brand}</small></span><span data-label="Stops">{trip.stops}</span><span data-label="Temperature">{trip.temperature}</span><em className={`${styles.badge} ${trip.changed ? styles.planChanged : trip.status === "LOADED" ? styles.loaded : trip.loading ? styles.loading : styles.notStarted}`}>{trip.changed ? "!" : trip.status === "LOADED" ? "✓" : "◷"} {state}</em><Link href={`/workspace/loader/load?trip=${encodeURIComponent(trip.id)}`}>{trip.status === "LOADED" ? "View" : trip.loading ? "Continue" : "Open"}</Link></article>; })}</div>{!visible.length && <p>No trips match these filters.</p>}</section></>;
}
