import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";

const roles = [["Store Manager", "Place and track outlet orders, see planned arrivals and confirm receipt.", "Desktop · Phone"], ["Dispatcher", "Build feasible delivery plans, explain deferrals and monitor live execution.", "Desktop"], ["Loader", "Load trips against the published plan and flag shortfalls before departure.", "Tablet · Shared terminal"], ["Driver", "Run your assigned route safely, capture proof of delivery and keep working offline.", "Phone"]];
const steps = [["Store order", "Outlet places and confirms an order before cutoff."], ["Dispatcher plan", "Suggested plan is checked against vehicle and delivery rules, then published."], ["Loader hand-off", "Trip loaded in sequence; shortfalls flagged early."], ["Driver execution", "Guided stops with proof of delivery, online or offline."], ["Store receipt", "Receipt confirmed in full, short or damaged."], ["Issue resolution", "Evidence compared before any attribution."]];
const benefits = [["Plans you can explain", "Every suggested plan shows its reasons, and a dispatcher approves it before it’s published."], ["Nothing slips through", "Each order, load and delivery ends with a confirmation — or a clear way to retry."], ["Safer on the road", "Drivers see detailed actions only once they’ve safely stopped."], ["Fair issue resolution", "Loader counts, delivery proof and store receipts are compared before any decision."]];

export default function HomePage() { return <main className={styles.page}>
  <section className={styles.hero}><Image className={styles.heroImage} src="/Image/landing-hero.webp" fill priority alt="Delivery vehicles travelling between connected outlet locations" /><div className={styles.heroShade} /><nav className={styles.nav}><Image src="/Image/logo-white.png" width={133} height={37} alt="Waypoint" /><div><a href="#how-it-works">How it works</a><a href="#roles">Roles</a><Link href="/sign-in">Sign in</Link></div></nav><div className={styles.heroContent}><p className={styles.eyebrow}>DELIVERY OPERATIONS PLATFORM</p><h1>One shared workflow<br />from outlet order to<br />confirmed delivery.</h1><p>Plan, load, deliver and confirm every outlet order in one connected workspace — with clear status for everyone involved.</p><div className={styles.actions}><Link href="/sign-in">Sign in</Link><a href="#how-it-works">See how it works</a></div><div className={styles.statuses}><b>✓ Delivered</b><b>△ Deferred</b><b>⟳ Sync pending</b><span>Clear, shared status at every step</span></div></div><div className={styles.featureStrip}>{[["▣", "One record, end to end", "Orders, plans, loading, delivery and receipt share a single history."], ["◉", "Role-based access", "Everyone sees only their outlet, depot or assigned trip."], ["⌁", "Keeps working offline", "Drivers can deliver without signal; records sync automatically."], ["⟳", "Live status updates", "Plan changes and delivery events reach the right people as they happen."]].map(([icon,title,text]) => <article key={title}><i>{icon}</i><strong>{title}</strong><p>{text}</p></article>)}</div></section>
  <section className={styles.section} id="roles"><p className={styles.eyebrow}>ROLES</p><h2>Four roles. One shared system.</h2><p className={styles.lead}>Each role signs in to its own workspace, with the same status vocabulary, data and audit trail.</p><div className={styles.cards}>{roles.map(([title,text,device], index) => <Link href={`/sign-in?role=${["store_manager","dispatcher","loader","driver"][index]}`} key={title}><i>{["▣","▦","◇","▰"][index]}</i><h3>{title}</h3><p>{text}</p><b>{device}<span>→</span></b></Link>)}</div></section>
  <section className={`${styles.section} ${styles.workflow}`} id="how-it-works"><p className={styles.eyebrow}>HOW IT WORKS</p><h2>One loop from order to resolution</h2><div className={styles.steps}>{steps.map(([title,text], index) => <article key={title}><i>{index + 1}</i><h3>{title}</h3><p>{text}</p></article>)}</div><small>♢ Every stage writes to one shared audit trail — changes are never silently overwritten.</small></section>
  <section className={styles.section}><p className={styles.eyebrow}>WHY WAYPOINT</p><h2>Built for everyday delivery operations</h2><div className={styles.cards}>{benefits.map(([title,text], index) => <article key={title}><i>{["☷","✓","♢","ⓘ"][index]}</i><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className={styles.cta}><h2>Ready to get started?</h2><p>Sign in with the account your administrator set up for you.</p><Link href="/sign-in">Sign in</Link></section><footer><Image src="/Image/logo-white.png" width={133} height={37} alt="Waypoint" /><div>Help centre　 Contact support　 Privacy　 Terms of use</div><span>© 2026 Waypoint. All rights reserved.</span></footer></main>; }
