import Link from "next/link";
import { prisma } from "@waypoint/database";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireRole } from "@/lib/auth";
import { displayDate, label } from "@/lib/format";
import styles from "./change.module.css";

export default async function LoaderChangePage() {
  const session = await requireRole("loader");
  const plan = session.depotId ? await prisma.plan.findFirst({ where: { depotId: session.depotId, status: "PUBLISHED" }, include: { trips: { include: { allocations: { include: { order: true }, orderBy: { sequence: "desc" } } } } }, orderBy: [{ serviceDate: "desc" }, { version: "desc" }] }) : null;
  const previous = plan && plan.version > 1 ? await prisma.plan.findFirst({ where: { depotId: plan.depotId, serviceDate: plan.serviceDate, version: { lt: plan.version } }, include: { trips: { include: { allocations: true, vehicle: true } } }, orderBy: { version: "desc" } }) : null;
  return <WorkspaceShell role="loader" active="Trip queue"><section className={styles.changePage}><Link href="/workspace/loader">← Trip queue</Link><header className={styles.heading}><h1>Plan changes and re-verification</h1><p>{plan ? `Plan v${plan.version} · ${displayDate(plan.serviceDate)}` : "No published plan"}</p></header>{plan && plan.version > 1 ? <><section className={styles.alert}><b>Check the latest published loading sequence</b><span>Confirm each trip against this version before handoff.</span></section><div className={styles.compare}><article className={styles.before}><h2>Before · {previous ? `Plan v${previous.version}` : "No previous record"}</h2>{previous?.trips.map((trip) => <p key={trip.id}>{trip.vehicleId} · {trip.district} · {trip.allocations.length} stops · {label(trip.status)}</p>)}</article><article className={styles.now}><h2>Now · Plan v{plan.version}</h2>{plan.trips.map((trip) => <p key={trip.id}>{trip.vehicleId} · {trip.district} · {trip.allocations.length} stops · {label(trip.status)}</p>)}</article></div>{plan.trips.map((trip) => <section className={styles.whatToDo} key={trip.id}><h2>{trip.vehicleId} · {trip.district}</h2><table><thead><tr><th>Stop</th><th>Outlet</th><th>Order</th><th>Units</th></tr></thead><tbody>{trip.allocations.map((allocation) => <tr key={allocation.id}><td>{allocation.sequence}</td><td>{allocation.order.outletId}</td><td>{allocation.orderId}</td><td>{allocation.order.units}</td></tr>)}</tbody></table><Link href={`/workspace/loader/load?trip=${encodeURIComponent(trip.id)}`}>Re-verify loading</Link></section>)}</> : <p>No published plan changes to review.</p>}</section></WorkspaceShell>;
}
