import Link from "next/link";
import { prisma } from "@waypoint/database";
import { WorkspaceShell } from "@/components/workspace-shell";
import { requireRole } from "@/lib/auth";
import { displayDate, label } from "@/lib/format";
import { ChangeAcknowledgement } from "./change-acknowledgement";
import styles from "./change.module.css";

export default async function LoaderChangePage() {
  const session = await requireRole("loader");
  const plan = session.depotId ? await prisma.plan.findFirst({ where: { depotId: session.depotId, status: "PUBLISHED" }, include: { trips: { include: { vehicle: true, allocations: { include: { order: true }, orderBy: { sequence: "desc" } } } } }, orderBy: [{ serviceDate: "desc" }, { version: "desc" }] }) : null;
  const previous = plan && plan.version > 1 ? await prisma.plan.findFirst({ where: { depotId: plan.depotId, serviceDate: plan.serviceDate, version: { lt: plan.version } }, include: { trips: { include: { allocations: true, vehicle: true } } }, orderBy: { version: "desc" } }) : null;
  const firstTrip = plan?.trips[0] ?? null;
  return <WorkspaceShell role="loader" active="Trip queue"><section className={styles.changePage}><Link className={styles.back} href="/workspace/loader">← Trip queue</Link><header className={styles.heading}><h1>Plan changes and re-verification</h1><p>{plan ? `Plan v${plan.version} · ${displayDate(plan.serviceDate)}` : "No published plan"}</p></header>{plan && plan.version > 1 ? <><section className={styles.alert}><b>Check the latest published loading sequence</b><span>Acknowledge this change, then verify every affected trip against the current vehicle and stop order.</span></section><div className={styles.compare}><article className={styles.before}><h2>Before · {previous ? `Plan v${previous.version}` : "No previous record"}</h2>{previous?.trips.map((trip) => <p key={trip.id}><strong>{trip.vehicleId} · {trip.district}</strong><span>{trip.allocations.length} stops · {label(trip.status)}</span></p>)}</article><article className={styles.now}><h2>Now · Plan v{plan.version}</h2>{plan.trips.map((trip) => <p key={trip.id}><strong>{trip.vehicleId} · {trip.district}</strong><span>{trip.allocations.length} stops · {label(trip.status)}</span></p>)}</article></div>{plan.trips.map((trip) => { const prior = previous?.trips.find((entry) => entry.brand === trip.brand && entry.district === trip.district && entry.tripNumber === trip.tripNumber); return <section className={styles.whatToDo} key={trip.id}><h2>{trip.vehicleId} · {trip.district}</h2><p className={styles.tripMeta}>{trip.vehicle.temperature === "REEFER" ? "Reefer" : "Ambient"} · {trip.allocations.length} stops{prior && prior.vehicleId !== trip.vehicleId ? ` · moved from ${prior.vehicleId}` : ""}</p><div className={styles.stopRows}>{trip.allocations.map((allocation, index) => <article className={prior && prior.vehicleId !== trip.vehicleId ? styles.moveRow : ""} key={allocation.id}><b>Load {index + 1}</b><span>Stop {allocation.sequence}</span><strong>{allocation.order.outletId}</strong><small>{allocation.orderId} · {allocation.order.units} units</small><em>{prior && prior.vehicleId !== trip.vehicleId ? `Move to ${trip.vehicleId}` : `Load on ${trip.vehicleId}`}</em></article>)}</div></section>; })}<ChangeAcknowledgement planId={plan.id} tripId={firstTrip?.id ?? null} /></> : <p>No published plan changes to review.</p>}</section></WorkspaceShell>;
}
